version: '3.3'
services:
  database:
    container_name: postgres
    image: postgres:16.1-alpine3.19
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    env_file: 
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"]
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    restart: always
 
volumes:
  pgdata:
